name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]

    name: CI Node ${{ matrix.node }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Fix Formatting
        run: yarn style:fix & yarn lint:fix

      - name: Check Codestyle and Quality
        run: yarn style:check & yarn lint:check

      - name: Run Tests
        run: yarn test
